#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Import from the standard library
import argparse
from termcolor import colored

# Import from mlproject
import mlproject
from mlproject.distance import haversine



if __name__ == '__main__':
  parser = argparse.ArgumentParser(description='compute distance')

  parser.add_argument('--coords', nargs='+',
                   help='for use with x y coordinates', required = False)

  parser.add_argument('--prod',
                        action='store_true',
                        default=False,
                        help='to store the argument')
  args = parser.parse_args()
  lon1, lat1, lon2, lat2 = args.coords

  distance = haversine(float(lon1), float(lat1), float(lon2), float(lat2))
  print(colored(str(distance), "blue"))
